imports:
    - { resource: config.yml }

swiftmailer:
    spool:
        type: file

chaplean_mailer:
    bcc_address: ''
    sender_address: ''
    sender_name: ''
    subject:
        prefix: '[TEST]'
    test: true
